services:
  - type: web
    name: movie-review-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn movie_review_app.app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9